# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: cart
      MYSQL_PASSWORD: root


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: cart-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - db
